Feat(be): user session token
boostcampwm-2024/web07-Ask-It pull request #50
Opened 2024-11-09 23:05 UTC by shl0501

## 개요
- session-user 사이의 토큰 발급 및 검사 기능을 구현했습니다.

## 추가내용
예외처리하는 기준을 클라이언트가 토큰을 무단으로 수정, 삭제, 생성 한 경우에 대해서 처리하였습니다. 예외처리 방법은 해당 이슈에 기록해놓았습니다.

추후 예외처리가 더 필요할 경우 추가로 구현하겠습니다.
 
## 이슈
- close #37

2024-11-10 03:46 UTC, wlgh1553 commented
아니 이걸 벌써 끝내셨습니까...ㄷㄷ 고생하셨습니다! 코드 꼼꼼히 읽어볼게요!

[PR 제목 규칙](https://github.com/boostcampwm-2024/web07-Ask-It/wiki/%EA%B7%B8%EB%9D%BC%EC%9A%B4%EB%93%9C-%EB%A3%B0#pull-request-%EA%B7%9C%EC%B9%99) 한번만 참고해주시면 좋을 것 같아요!

2024-11-10 04:23 UTC, cjeongmin requested changes
고생 많으셨습니다! 어제 밤에 늦게 이야기한건데, 이렇게 빨리 올라올 줄은 몰랐습니다...

이건 중요한건 아닌데, 제가 `logined` 라는 단어가 어색해서 좀 찾아봤는데 'log in'은 동사이고, 'login'은 명사, 'logged in'은 과거형이라고 하더라구요. 영어 너무 어렵습니다...

2024-11-10 04:23 UTC, cjeongmin commented on apps/server/src/sessions-auth/sessions-auth.service.ts
> +      const result = await this.sessionsAuthRepository.findToken(user_id, session_id, token);
`generateTokenForLogined` 함수 안에, `findToken` 을 이용해서 리턴을 해주기 때문에 필요없지 않을까요?

2024-11-10 04:23 UTC, cjeongmin commented on apps/server/src/sessions-auth/sessions-auth.service.ts
> +      return result || (await this.sessionsAuthRepository.generateTokenForNotLogined({ ...data }));
`generateTokenForNotLogined` 함수에 인자를 전달할 때 `data` 가 아닌 `{ ...data }`인 이유가 있나요?

2024-11-10 04:23 UTC, cjeongmin commented on apps/server/src/sessions-auth/sessions-auth.repository.ts
> +  async generateTokenForNotLogined(data: SessionAuthDto) {
조금 더 일반화된 이름이 좋지 않을까요? `generateTokenForLogined` 함수에서도 사용하니 이름을 다르게 지어도 좋을 것 같습니다!

2024-11-10 04:49 UTC, shl0501 commented on apps/server/src/sessions-auth/sessions-auth.service.ts
> +      return result || (await this.sessionsAuthRepository.generateTokenForNotLogined({ ...data }));
data에 해당하는 sessionAuthDto 내부의 값이 바뀔 경우, 바뀐 값으로 덮어씌어서 전달해주고자 ...data로 전달했는데, 다시 생각해보니 data로만 전달해도 될 것 같습니다.
감사합니다.

2024-11-10 04:53 UTC, shl0501 commented on apps/server/src/sessions-auth/sessions-auth.repository.ts
> +  async generateTokenForNotLogined(data: SessionAuthDto) {
generateToken으로 변경하였습니다!

2024-11-10 05:02 UTC, shl0501 commented on apps/server/src/sessions-auth/sessions-auth.service.ts
> +      const result = await this.sessionsAuthRepository.findToken(user_id, session_id, token);
완전 놓치고 있던 부분이었는데... 감사합니다!

2024-11-10 11:22 UTC, yu-yj215 requested changes

2024-11-10 11:22 UTC, yu-yj215 commented on apps/server/prisma/migrations/20241109165716_init/migration.sql
> +
user_id는 null이 가능하게 하기로했는데, 실제 쿼리는 저런식으로 들어가네요

2024-11-10 14:28 UTC, shl0501 commented on apps/server/prisma/migrations/20241109165716_init/migration.sql
> +
prisma.schema에서 type 뒤에 ?를 붙이면 nullable이 된다고 해서 추개했습니다!

2024-11-10 22:29 UTC, cjeongmin reviewed
PR 제목 대문자에서 소문자로 변경 부탁드립니다!

2024-11-10 22:30 UTC, cjeongmin approved these changes
LGTM👍

2024-11-11 00:52 UTC, yu-yj215 approved these changes

2024-11-11 00:53 UTC, merged